### ISSUE TITLE
Unable to login error message

### ISSUE THREAD

**Issue by noneck** [BetaNYC/talk.beta.nyc#1]
@jqnatividad this is the second time I've seen this message.

It appears when people go to activate their accounts, they get the following error message. Not sure what is up with authorization.

![screen shot 2015-07-20 at 7 20 03 pm](https://cloud.githubusercontent.com/assets/94735/8789980/5657b926-2f16-11e5-8235-5a9d39c79919.png)

**Comment by jqnatividad** [comment]
@noneck, it appears that Google OAuth2 login got misconfigured, and I had to re-enable Contacts API and Google+ API. 

https://meta.discourse.org/t/configuring-google-oauth2-login-for-discourse/15858

I've checked and its now working again.
